using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Uroboros.syntax.reading
{
    public enum TokenType
    {
        Add,
        And,
        Ask,
        By,
        Copy,
        Create,
        Cut,
        Delete,
        Directory,
        Drop,
        Each,
        Else,
        File,
        First,
        For,
        Force,
        From,
        If,
        In,
        Last,
        Like,
        Move,
        Open,
        Or,
        Order,
        Print,
        Remove,
        Rename,
        Reverse,
        Run,
        Select,
        Skip,
        Sleep,
        To,
        Where,
        While,
        With,
        Without,
        Xor,

        Variable,
        StringConstant,
        NumericConstant,
        BoolConstant,

        Comma,
        Exclamation,
        Equals,
        Smaller,
        Bigger,
        BracketOn,
        BracketOff,
        CurlyBracketOn,
        CurlyBracketOff,
        SquareBracketOn,
        SquareBracketOff,
        Colon,
        Semicolon,
        Plus,
        Minus,
        Multiply,
        Divide,
        Percent,

        PlusPlus,
        MinusMinus,
        NotEquals,
        BiggerOrEquals,
        SmallerOrEquals,
        Arrow,
        PlusEquals,
        MinusEquals,
        MultiplyEquals,
        DivideEquals,
        PercentEquals,

        CreateFile,
        CreateDirectory,
        ForceTo,
        OrderBy,

        Null
    }
}
